In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from xgboost.sklearn import XGBRegressor
from xgboost.sklearn import XGBClassifier
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import OneHotEncoder
import numpy
import xlrd

In [3]:
raw_df = pd.read_csv("data.csv", header = None)
raw_df.rename(columns = {0:'Ae', 1:'Ap', 2:'Rs', 3:'Fz', 4:'label'}, inplace = True)

In [4]:
def re_cate(label):
    if label >2:
        return 1
    else:
        return 0

In [5]:
raw_df['label'] = raw_df.apply(lambda x : re_cate(x.label), axis = 1)

In [47]:
raw_df

Ae   Ap     Rs    Fz  label
0    5.0  2.5   4000  0.05      0
1    5.0  2.5   4500  0.05      0
2    5.0  2.5   5000  0.05      0
3    5.0  2.5   5500  0.05      0
4    5.0  2.5   6000  0.05      0
5    5.0  2.5   6500  0.05      0
6    5.0  2.5   7000  0.05      0
7    5.0  2.5   7500  0.05      0
8    5.0  2.5   8000  0.05      0
9    5.0  2.5   8500  0.05      0
10   5.0  2.5   9000  0.05      0
11   5.0  2.5   9500  0.05      0
12   5.0  2.5  10000  0.05      0
13   5.0  2.5  10500  0.05      0
14   5.0  2.5  11000  0.05      0
15   5.0  2.5  11500  0.05      0
16   5.0  2.5  12000  0.05      0
17   5.0  2.5  12500  0.05      0
18   5.0  2.5  13000  0.05      0
19   5.0  2.0   4000  0.05      0
20   5.0  2.0   4500  0.05      0
21   5.0  2.0   5000  0.05      0
22   5.0  2.0   5500  0.05      0
23   5.0  2.0   6000  0.05      0
24   5.0  2.0   6500  0.05      0
25   5.0  2.0   7000  0.05      0
26   5.0  2.0   7500  0.05      0
27   5.0  2.0   8000  0.05      0
28   5.0  2.0   8500  0.05      0
29   5.0  2.0   9000  0.05      0
..   ...  ...    ...   ...    ...
350  0.5  9.0   8000  0.05      1
351  0.5  9.0   8500  0.05      0
352  0.5  9.0   9000  0.05      1
353  0.5  9.0   9500  0.05      1
354  0.5  9.0  10000  0.05      1
355  0.5  9.0  10500  0.05      0
356  0.5  9.0  11000  0.05      0
357  0.5  9.0  11500  0.05      1
358  0.5  9.0  12000  0.05      1
359  0.5  9.0  12500  0.05      1
360  0.5  9.0  13000  0.05      1
361  0.5  6.0   4000  0.05      1
362  0.5  6.0   4500  0.05      1
363  0.5  6.0   5000  0.05      1
364  0.5  6.0   5500  0.05      1
365  0.5  6.0   6000  0.05      1
366  0.5  6.0   6500  0.05      1
367  0.5  6.0   7000  0.05      1
368  0.5  6.0   7500  0.05      1
369  0.5  6.0   8000  0.05      1
370  0.5  6.0   8500  0.05      1
371  0.5  6.0   9000  0.05      1
372  0.5  6.0   9500  0.05      1
373  0.5  6.0  10000  0.05      1
374  0.5  6.0  10500  0.05      1
375  0.5  6.0  11000  0.05      1
376  0.5  6.0  11500  0.05      1
377  0.5  6.0  12000  0.05      1
378  0.5  6.0  12500  0.05      1
379  0.5  6.0  13000  0.05      1

[380 rows x 5 columns]

In [6]:
raw_matrix = raw_df.as_matrix()
raw_feature = raw_matrix[:, 0:-3]
raw_rs = raw_matrix[:, -3]
raw_label = raw_matrix[:, -1]
raw_feature_mean = raw_feature.mean(axis = 0)
raw_feature_std = raw_feature.std(axis = 0)
raw_feature_normalized = (raw_feature - raw_feature_mean)/raw_feature_std

F:\Anaconda\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [7]:
raw_mix = np.column_stack((raw_feature_normalized, raw_label))

In [8]:
raw_mix

array([[ 1.12115264, -0.50296946,  0.        ],
       [ 1.12115264, -0.50296946,  0.        ],
       [ 1.12115264, -0.50296946,  0.        ],
       ...,
       [-1.56961369,  0.23824869,  1.        ],
       [-1.56961369,  0.23824869,  1.        ],
       [-1.56961369,  0.23824869,  1.        ]])

In [9]:
xgb = XGBRegressor(
                        #booster = 'gblinear',
                        #objective='multi:softmax',
                        #num_class=7,#必须要考虑到0的情况。这个数据集里面没有零
                        #n_estimators=5,
                        max_depth=4,
                        min_child_weight = 5,
                        scale_pos_weight = 5,
                        num_boost_round =5,
                        max_delta_step=1000,
                        alpha =2,
                        eta=1
                        #colsample_bytree=0.9
                        #gamma=5,
                        #process_type='update'
                        )

In [26]:
xgb = XGBRegressor()

In [27]:
raw_feature_mean

array([3.125, 4.875])

In [28]:
raw_feature_std

array([1.67238602, 4.72195669])

In [29]:
xgb.fit(raw_mix,raw_rs)

[22:09:33] WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0,
       importance_type='gain', learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=None, subsample=1, verbosity=1)

In [30]:
input_sample = [[4.0,3.5],[4.0, 3.0],[4.0, 2.5],[4.0, 2.0],[4.0, 1.5]]
input_sample = (input_sample - raw_feature_mean)/raw_feature_std
input_sample1 = np.column_stack((input_sample,[0,0,0,0,0]))
input_sample2 = np.column_stack((input_sample,[1,1,1,1,1]))

In [31]:
input_sample1

array([[ 0.52320456, -0.29119284,  0.        ],
       [ 0.52320456, -0.39708115,  0.        ],
       [ 0.52320456, -0.50296946,  0.        ],
       [ 0.52320456, -0.60885777,  0.        ],
       [ 0.52320456, -0.71474607,  0.        ]])

In [32]:
input_sample2

array([[ 0.52320456, -0.29119284,  1.        ],
       [ 0.52320456, -0.39708115,  1.        ],
       [ 0.52320456, -0.50296946,  1.        ],
       [ 0.52320456, -0.60885777,  1.        ],
       [ 0.52320456, -0.71474607,  1.        ]])

In [33]:
pred_smile_label = xgb.predict(input_sample1)

In [34]:
pred_smile_label

array([7777.329 , 7904.6816, 7822.9565, 8005.434 , 8640.791 ],
      dtype=float32)

In [35]:
pred_smile_label = xgb.predict(input_sample2)

In [36]:
pred_smile_label

array([10848.076 ,  9296.788 ,  9135.7295,  8728.269 ,  8452.16  ],
      dtype=float32)

In [37]:
input_sample = [[5.0,2.5],[5.0, 2.0],[5.0, 1.5],[5.0, 1.0],[5.0, 0.5]]
input_sample = (input_sample - raw_feature_mean)/raw_feature_std
input_sample1 = np.column_stack((input_sample,[0,0,0,0,0]))
input_sample2 = np.column_stack((input_sample,[1,1,1,1,1]))

In [38]:
pred_smile_label = xgb.predict(input_sample1)

In [39]:
pred_smile_label

array([8407.151 , 7832.248 , 7877.1504, 7786.657 , 7624.081 ],
      dtype=float32)

In [40]:
pred_smile_label = xgb.predict(input_sample2)

In [41]:
pred_smile_label

array([11725.52 , 11038.185,  9251.143,  8931.296,  8528.826],
      dtype=float32)

In [42]:
input_sample = [[3.0,4.5],[3.0, 4.0],[3.0, 3.5],[3.0, 3.0],[3.0, 2.5]]
input_sample = (input_sample - raw_feature_mean)/raw_feature_std
input_sample1 = np.column_stack((input_sample,[0,0,0,0,0]))
input_sample2 = np.column_stack((input_sample,[1,1,1,1,1]))

In [43]:
pred_smile_label = xgb.predict(input_sample1)

In [44]:
pred_smile_label

array([7661.887 , 7552.8384, 7946.37  , 7947.881 , 7866.156 ],
      dtype=float32)

In [45]:
pred_smile_label = xgb.predict(input_sample2)

In [46]:
pred_smile_label

array([11227.514, 10560.329,  8814.716,  8704.102,  8543.043],
      dtype=float32)